import{a as d,S as P,i as c}from"./assets/vendor-BIqUfTm7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const $="57677215-5b9f79ed07fc95428f21aaa62",f=15;d.defaults.baseURL="https://pixabay.com/api/";async function m(e,o){return(await d.get("",{params:{key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:f}})).data}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector("#load-more"),B=new P(".gallery a",{captionsData:"alt",captionDelay:250});function p(e){const o=e.map(({webformatURL:i,largeImageURL:n,tags:t,likes:r,views:s,comments:v,downloads:M})=>`<li class="gallery-item">
  <a class="gallery-link" href="${n}">
    <img class="gallery-image" src="${i}" alt="${t}" />
  </a>
  <ul class="info">
    <li><b>Likes</b>${r}</li>
    <li><b>Views</b>${s}</li>
    <li><b>Comments</b>${v}</li>
    <li><b>Downloads</b>${M}</li>
  </ul>
</li>`).join("");y.insertAdjacentHTML("beforeend",o),B.refresh()}function E(){y.innerHTML=""}function L(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function w(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const R=document.querySelector(".form"),O=document.querySelector("#load-more");let l="",a=1;R.addEventListener("submit",x);O.addEventListener("click",A);async function x(e){if(e.preventDefault(),l=e.currentTarget.elements["search-text"].value.trim(),!l){c.warning({message:"Please enter a search query.",position:"topRight"});return}a=1,E(),u(),L();try{const o=await m(l,a);if(o.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(o.hits),q(o.totalHits)}catch(o){S(o)}finally{b()}}async function A(){a+=1,u(),L();try{const e=await m(l,a);p(e.hits),q(e.totalHits),D()}catch(e){a-=1,w(),S(e)}finally{b()}}function q(e){a*f>=e?(u(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}function D(){const e=document.querySelector(".gallery-item"),{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}function S(e){c.error({message:e.message,position:"topRight"})}
//# sourceMappingURL=index.js.map
